### ISSUE TITLE
Clique sur bouton : rien ne se passe

### ISSUE THREAD

**Issue by CyrilCharlier** [chteuchteu/Material-Freebox-OS#1]
![2016-04-14_18h29_14](https://cloud.githubusercontent.com/assets/11455745/14535599/cd7732f8-026e-11e6-9291-61e6277f89be.png)

Lorsque je clique sur n'importe quelle icone, aucune fenêtre ne s'ouvre. Via le menu en bas à gauche cela marche par contre

**Comment by quentin-st** [comment]
Merci pour le bug report !
Avez-vous essayé de double-cliquer sur l'icône ? C'est le comportement par défaut de Freebox OS, je ne l'ai pas changé

**Comment by CyrilCharlier** [comment]
Oups, c'est double clique,j'avais oublié... désolé !

**Comment by CyrilCharlier** [comment]
Peut être une option pour changer ça ? ;)

**Comment by quentin-st** [comment]
Je pense que c'est la faute au curseur : le pointeur (![image](https://cloud.githubusercontent.com/assets/1551971/14535730/8be34b46-026f-11e6-97c8-e1859d73fa2b.png)) fait penser que c'est un lien clickable (et non pas double-clickable), passer ça en curseur normal (![image](https://cloud.githubusercontent.com/assets/1551971/14535747/a12055bc-026f-11e6-99a4-fa36b4deb94e.png)) devrait moins perturber l'utilisateur !

Merci pour le retour !
Je vais effectuer le changement, il sera visible à la prochaine mise à jour de l'extension.

**Comment by CyrilCharlier** [comment]
Super merci. Je vais voir pour faire des propositions via fork et PR si cela peut intéresser
