### ISSUE TITLE
Incohérence logo partage

### ISSUE THREAD

**Issue by chbozzi** [chteuchteu/Material-Freebox-OS#10]
Bonjour,
Dans les paramètres avancés, plus particulièrement la section de partage, le logo Windows représente bien sa section, mais je me disais qu'un laptop générique ne représentait pas vraiment le partage mac. J'ai vu qu'il y avait un logo apple dans les dispo, ce serait pas plus logique de l'utiliser pour cette section?
![image](https://user-images.githubusercontent.com/38192289/38472822-f0ddc8c2-3b85-11e8-9f27-0b7ae3ecb3ab.png)

Merci :)

**Comment by quentin-st** [comment]
Merci pour ce retour !
Nous utilisons actuellement l'icône `mdi-laptop-mac`, mais qui ressemble en effet beaucoup à un laptop générique

J'hésite entre `mdi-apple` et `mdi-apple-finder`, qu'en penses-vous ?

![screenshot from 2018-04-09 15-46-09](https://user-images.githubusercontent.com/1551971/38501401-32cd3bb4-3c0d-11e8-93b0-b5b180465a02.png)

**Comment by chbozzi** [comment]
Je dirais la première (mdi-apple) car elle représente l'OS, qui je pense serait plus logique par rapport au logo Windows à côté?

**Comment by quentin-st** [comment]
Bien vu ! :-) Je viens de faire la modif, elle sera déployée lors d'une prochaine mise à jour de l'extension.

Merci pour votre avis !
