### ISSUE TITLE
Bing Daily Wallpaper

### ISSUE THREAD

**Issue by slc66** [chteuchteu/Material-Freebox-OS#12]
Bonjour,

Tout d'abord, **bravo** et **merci** pour **ce superbe travail**.

Je joue un peu avec Python et je me demande pourquoi la modeste page que j'ai développé ne permet pas d'afficher l'image voulue.

Peut être pourras tu me donner une piste, elle se trouve ici [DailyBingWallpaper](https://slc66.myqnapcloud.com/DailyBingWallpaper.html
)

**Comment by saouinet** [comment]
Désolé pour la reponse tardive... je ne sus pas le createur de ce code. Merci de demander à un ds développeurs à l'origine du projet.
Cordialement.

**Comment by quentin-st** [comment]
@slc66 : Ceci n'est pas une issue qui concerne directement Material-Freebox-OS
Pour ce genre de questions, je te concerne de te tourner vers StackOverflow
Au vu du lien que tu as partagé, ton problème semble résolu ;)

**Comment by slc66** [comment]
@chteuchteu Bonjour, je vais poser ma question différemment. Pourquoi, lorsque je mets l'URL [DailyBingWallpaper](https://slc66.myqnapcloud.com/DailyBingWallpaper.html) dans la conf du module, le fond d'écran est noire ? L'image est-elle trop grande ? Merci

**Comment by quentin-st** [comment]
@slc66 L'extension s'attend à recevoir l'URL d'une image (https://www.bing.com/az/hprichbg/rb/FranceMenton_FR-FR10017039275_1920x1080.jpg par exemple), et non pas l'URL d'une page web :-)
