### ISSUE TITLE
Léger souci cosmétique dans VPN

### ISSUE THREAD

**Issue by CyrilCharlier** [chteuchteu/Material-Freebox-OS#2]
![2016-04-14_19h00_47](https://cloud.githubusercontent.com/assets/11455745/14536549/4188f9c0-0273-11e6-811a-c0cb5e99c04c.png)

Comme le montre le Screen, un léger bug dans l'affichage de la fenetre VPN (Paramètre de la freebox > Serveur VPN)

**Comment by quentin-st** [comment]
Corrigé, merci !
