### ISSUE TITLE
Support changing background & primary/accent colors on Firefox

### ISSUE THREAD

**Issue by quentin-st** [chteuchteu/Material-Freebox-OS#4]
Due to Firefox's partial support of `chrome.storage` ([see here](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Chrome_incompatibilities#storage)), we cannot use background changing feature.

The underlaying issue is the [unability to access chrome.storage from content scripts](https://bugzilla.mozilla.org/show_bug.cgi?id=1197475).

This will be supported on Chrome, but not on Firefox for now. A visual indication will encourage the user to use Google Chrome instead.

**Comment by quentin-st** [comment]
![Not available for Firefox](https://cloud.githubusercontent.com/assets/1551971/14762177/8583d6ce-0974-11e6-9fda-31da720030c0.png)

**Comment by MrMitch** [comment]
Have you looked at Firefox's [Background scripts](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Anatomy_of_a_WebExtension#Background_scripts) ?
They are able to use the storage API.

**Comment by MrMitch** [comment]
You can also communicate between content scripts and background scripts : https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Content_scripts#Communicating_with_background_scripts

**Comment by quentin-st** [comment]
Thanks for the idea!

I created a simple background script whose aim is to access local storage (set and retrieve values):

``` javascript
// background-script.js

var BackgroundScript = {
    getLocalStorageValue: function(key, onceLoaded) {
        chrome.storage.local.get(key, function (data) {
            onceLoaded(data[key]);
        });
    },
    setLocalStorageValues: function(values) {
        chrome.storage.local.set(values);
    }
};
```

and defined it in the `manifest.json`:

``` json
"background": {
    "scripts": ["data/js/background-script.js"]
},
```

This background script can be called from our browser action JS:

### 1. By accessing it directly, [as shown in the Chrome documentation](https://developer.chrome.com/extensions/background_pages#example):

``` javascript
// browser-action/js/script.js

// var BrowserAction = {
findBackgroundScriptReference: function() {
    var backgroundScript = null;

    chrome.extension.getViews().forEach(function(view) {
        if (view.BackgroundScript !== undefined)
            backgroundScript = view.BackgroundScript;
    });

    return backgroundScript;
},
// ...

var backgroundScript = BrowserAction.findBackgroundScriptReference();

backgroundScript.setLocalStorageValues({
    'color-primary': primary,
    'color-accent': accent
});
```

### 2. Using the [messaging API](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Content_scripts#Communicating_with_background_scripts)

Both solutions works fine on Chrome, but fails on Firefox:
1. Will fail with the same behavior than the one documented in this issue
2. Will fail even harder:

![screenshot from 2016-05-20 23-14-50](https://cloud.githubusercontent.com/assets/1551971/15442334/b37b54ae-1ee0-11e6-9a2f-d30056f10933.png)

WebExtensions are quite new on Firefox: I'm afraid our best chance for now is to wait for it to be correctly supported

**Comment by quentin-st** [comment]
I think I found a way. As suggested by [this comment](https://bugs.chromium.org/p/chromium/issues/detail?id=30224#c9), we could use the HTML5 localStorage (instead of the extension's localStorage) in a background page. We would communicate with it to store / retrieve key-value pairs.

It works fine from the browser-action on Chrome, I'll still have to try on Firefox.
