### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by loic-martinez-freelance** [chteuchteu/Material-Freebox-OS#5]
What is the purpose of the new permissions required in google chrome ?

**Comment by quentin-st** [comment]
Hi,

The [background changer feature](https://raw.githubusercontent.com/chteuchteu/Material-Freebox-OS/master/doc/screenshot3.png) needs to
- be able to access current tab from browser-action (to update the wallpaper when updated in browser-action) (`tabs`)
- locally store the chosen wallpaper (`storage`)

These permissions are used in browser-action [`script.js` file](https://github.com/chteuchteu/Material-Freebox-OS/blob/master/data/browser-action/js/script.js).
