### ISSUE TITLE
Opera browser

### ISSUE THREAD

**Issue by fujisan43** [chteuchteu/Material-Freebox-OS#7]
Hi,
Would it work on Opera browser?
F.

**Comment by quentin-st** [comment]
Hi! 

For now, an Opera specific extension isn't planned. 
Though, you may be able to install the Chrome extension on your Opera browser -  I haven't tested it, could you? 

Please provide feedback if you try! I'll document it if it works. 

Thanks!

**Comment by fujisan43** [comment]
I did install it actually but it doesn't work properly. Only the background image is shown.

**Comment by quentin-st** [comment]
I just tried with Opera 37.0 using the [Download Chrome Extension](https://addons.opera.com/fr/extensions/details/download-chrome-extension-9/?display=en) and it works fine. I'll document the procedure.

How did you install it?

**Comment by fujisan43** [comment]
I cloned your git repo and opened the source directory in opera browser in the developper mode. That did not work. Your way works a lot better. Thanks.
