### ISSUE TITLE
Utiliser le flux TNT pour une fois ?

### ISSUE THREAD

**Issue by raphaelp-github** [chteuchteu/Material-Freebox-OS#8]
Vu sur UF.com, j'ai commencé à utiliser ton extension Firefox, c'est top. 

En ayant vu ce que tu as pu faire avec le code Javascript, je me suis demandé si par hasard, il y aurait moyen de contourner la problématique du lecteur plugin VLC ? Le plugin VLC pour Firefox n'est plus mis à jour depuis un moment. Je crois que c'est pour éviter les failles de sécurité. Il n'est plus disponible en ce moment.

A travers du code, n'a t'il pas moyen de forcer l'utilisation du flux en passant par le logiciel VLC lui-même ? Même si cela nous expose aux failles (faire une coche "à vos risques et périls" par exemple).

Capture d'écran : [https://screenshots.firefox.com/qfNaWjzjsWKjSvXm/192.168.1.254](https://screenshots.firefox.com/qfNaWjzjsWKjSvXm/192.168.1.254)

Merci !

**Comment by quentin-st** [comment]
Merci !

Le plus simple serait de directement lire le flux vidéo mis à disposition par Free dans VLC, sans passer par le navigateur ni Freebox OS, en suivant les instructions sur leur site officiel : [Regarder la télévision sur votre ordinateur (multiposte)](http://www.free.fr/assistance/100.html)

Je ferme cette issue puisqu'elle ne concerne pas directement Material Freebox OS !
