### ISSUE TITLE
Absence des nouveaux logos de la mise a jour 3.5 de FbOS et autres bugs

### ISSUE THREAD

**Issue by DrumSlayers** [chteuchteu/Material-Freebox-OS#9]
Bonjour,
Depuis la mise a jour 3.5 de freeboxOS, de nouveaux menus sont apparus avec de nouveaux logos
(Wifi Invité, WPS, QR Code, Choix carte, etc...)
Ces logos sont absent de material freebox bien évidemment, la request serait de les ajouter.
Egalement il y'a certains menus ou l'ont peut choisir son réseau (wifi/ethernet pour voir les périphériques) et le bouton pour selectionner est caché dans la barre de titre, problème de css j'imagine

Voila, c'est tout.
merci beaucoup.

**Comment by quentin-st** [comment]
Bonjour,

Merci pour ce rapport de bug ! Je n'ai pas encore effectué la mise à jour sur ma Freebox de test - je corrigerai tout ça quand ça sera le cas, je posterai des infos ici :-)

Merci !

**Comment by quentin-st** [comment]
Je viens de publier une mise à jour de l'extension qui vise à améliorer les icônes introduites par la récente mise à jour de Freebox OS.

N'hésitez pas à réouvrir cette issue si vous rencontrez encore des problèmes de design (en incluant si possible des captures d'écran et les étapes pour reproduire le problème).

Bonne soirée !
